# Generated by Django 5.0.2 on 2024-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment_authorization_id_payment_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged',
            field=models.BooleanField(default=False),
        ),
    ]
