# Generated by Django 5.0.2 on 2024-07-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_delivered_at_order_packaged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('controller', 'Via Controller')], default='online', max_length=20),
        ),
    ]
