# Generated by Django 5.0.2 on 2024-07-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference_id',
            new_name='invoice_id',
        ),
    ]
