# Generated by Django 5.0.2 on 2024-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_city_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
