# Generated by Django 5.0.2 on 2024-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('PM', 'Product Manager'), ('SE', 'Software Engineer'), ('QA', 'Quality Assurance'), ('UX', 'UX/UI Designer'), ('SA', 'Sales Associate'), ('CS', 'Customer Support'), ('HR', 'Human Resources'), ('LOG', 'Logistics Manager'), ('MK', 'Marketing Specialist'), ('AN', 'Data Analyst')], max_length=255, null=True, verbose_name='مسمي وظيفي'),
        ),
    ]
