# Generated by Django 5.0.2 on 2024-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.AddField(
            model_name='user',
            name='job_position_title',
            field=models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('PM', 'Product Manager'), ('SE', 'Software Engineer'), ('QA', 'Quality Assurance'), ('UX', 'UX/UI Designer'), ('SA', 'Sales Associate'), ('CS', 'Customer Support'), ('HR', 'Human Resources'), ('LOG', 'Logistics Manager'), ('MK', 'Marketing Specialist'), ('AN', 'Data Analyst')], default='SA', max_length=255, null=True, verbose_name='مسمي وظيفي'),
        ),
    ]
