# Generated by Django 5.0.2 on 2024-07-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_job_title_user_job_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.TextField(blank=True, null=True, verbose_name='User Info'),
        ),
    ]
